#!/bin/bash

#il pacchetto requests non è presente per default
apt-get install python3-requests
apt-get install ffmpeg

#il pacchetto youtube-dl non è presente per default
wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
chmod a+rx /usr/local/bin/youtube-dl


